config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts do
    resources :comments
    post '/soft_destroy' => 'comments#soft_destroy', :as => :comment_soft_destroy
  end
  post '/soft_destroy' => 'posts#soft_destroy', :as => :soft_destroy

  post '/restore' => 'trashes#restore' ,:as => :restore
  get '/trash' => 'trashes#index', :as => :trash
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  validates :post_id, presence: true
  validates :user_name, presence: true, length: {minimum: 2}
  validates :body,  presence: true
  include SoftDeletable

end

app/models/concerns/soft_deletable.rb
module SoftDeletable
  extend ActiveSupport::Concern

  included do
    scope :soft_destroyed, ->{ where(is_deleted: true) }
    scope :not_soft_destroyed, ->{ where(is_deleted: false) }
    scope :with_soft_destroyed, ->{ unscope(where: :is_deleted)}

    default_scope { with_soft_destroyed }
  end

  def soft_destroy
    update_column :is_deleted, true
  end

  def recover
    update_column :is_deleted, false
  end
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body,  presence: true
  include SoftDeletable

  scope :get_all_soft_deleted_comments, ->{ joins(:comments).where("comments.is_deleted =?",true).uniq }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    begin
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(params[:comment].permit(:user_name, :body, :post_id))
    respond_to do |format|
      format.html
      format.js   { render 'create.js.erb' }
    end
    rescue Exception => e
      redirect_to root_path, alert: e.message
    end
  end


  def edit
    begin
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    rescue Exception => e
      redirect_to root_path, alert: e.message
    end
  end

  def update
    begin
    @comment = Comment.find(params[:id])
    @comment.update!(params[:comment].permit(:user_name, :body, :post_id))
    respond_to do |format|
      format.html
      format.js   { render 'update.js.erb' }
    end
    rescue Exception => e
      redirect_to root_path, alert: e.message
      end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html
      format.js   { render 'destroy.js.erb' }
    end
  end

  def soft_destroy
    begin
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.soft_destroy
      respond_to do |format|
        format.html
        format.js   { render 'comments/soft_destroy.js.erb' }
      end

    rescue Exception => e
      redirect_to root_path, alert: e.message
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :soft_destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.not_soft_destroyed
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
        format.html
        format.js   { render 'show.js.erb' }
    end
  rescue Exception => e
    redirect_to root_path, alert: e.message
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  rescue Exception => e
    redirect_to root_path, alert: e.message
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html
        format.js   { render 'create.js.erb' }
      else
        @error = @post.errors.messages
        format.html { render :action => 'new' }
        format.js   { render 'fail_create.js.erb' }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html
        format.js   { render 'update.js.erb' }
      else
        @error = @post.errors.messages
        format.html { render :action => 'edit' }
        format.js   { render 'posts/failed_update.js.erb' }
      end
    end

  rescue Exception => e
    redirect_to root_path, alert: e.message
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    begin
    @post_id = @post.id
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.js   { render 'posts/destroy.js.erb' }
    end
    rescue Exception => e
      redirect_to root_path, alert: e.message
    end
  end

  def soft_destroy
    begin
      @post_id = @post.id
      @post.soft_destroy
      respond_to do |format|
        format.html
        format.js   { render 'posts/soft_destroy.js.erb' }
      end

  rescue Exception => e
    redirect_to root_path, alert: e.message
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      Exception.new("poast with id is not found") if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :is_deleted)
    end
end

app/controllers/trashes_controller.rb
class TrashesController < ApplicationController
  def index
    begin
    @posts = Post.soft_destroyed
    @deleted_comments = Post.get_all_soft_deleted_comments
    @map_comments_according_to_post = {}
    @deleted_comments.each do |post|
      comment = []
      post.comments.each do |com|
        comment << com
      end
      @map_comments_according_to_post[post.id] = comment
    end
    rescue Exception => e
      redirect_to trash_path, alert: e.message
    end
  end

  def restore
    begin
      if params[:post_id].present? && params[:id].present?
        @comment = Comment.find(params[:id])
        @comment.recover
      elsif params[:post_id].present?
        @post = Post.find(params[:post_id])
        @post.recover
      end
  rescue Exception => e
    redirect_to trash_path, alert: e.message
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/trashes_helper.rb
module TrashesHelper
end

app/views/comments/_comment.html.erb
  <div class="comment clearfix">
    <div class="comment_content">
      <p class="comment_body"><b><%= comment.user_name %></b></p>
      <p class="comment_body"><%= comment.body %></p>
      <p class="comment_time">
        <font size="2" color="blue"><%= time_ago_in_words(comment.created_at) %> Ago </font> </p>
    </div>
  <span style="display: inline;">
        <%= link_to 'Hard Delete', [comment.post, comment],
                       method: :delete,
                       class: "button",:remote => true,
                       data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Edit', edit_post_comment_path(comment.post, comment), remote: true %>
    <%= link_to 'Soft Delete',post_comment_soft_destroy_path(post_id: comment.post, id: comment.id), :remote => true, method: :post %>
    </span>
  </div>

app/views/comments/_form.html.erb
<%= form_for([post,comment], remote: true) do |f| %>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name , required: true %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body, required: true%><br>
    <br>

    <%= f.submit "#{comment.new_record? ? 'Submit' : 'Update'}", class: "btn btn-lg btn-primary", style: "padding: 4px 6px;
        font-size: 12px;" %>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<div id='comment_<%= @comment.id %>' > <%=j render :partial => 'comments/comment', :locals => {:comment => @comment }%> </div>");
$('#comment_count').empty().html("<%=j render partial: 'posts/post_comment_count', locals: {post: @post} %>");
$('.comment-form').empty().html("<%=j render partial: 'comments/form', locals: {post: @post, comment: @post.comments.build }%>");

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").remove();
$('#comment_count').empty().html("<%= render partial: 'posts/post_comment_count', locals: {post: @post} %>");

app/views/comments/edit.js.erb
$("#comment_<%= @comment.id %>").empty().html("<%=j render partial: 'comments/form', locals: {post: @post, comment: @comment }%>");

app/views/comments/soft_destroy.js.erb
$("#comment_<%= @comment.id %>").remove();
$('#comment_count').empty().html("<%= render partial: 'posts/post_comment_count', locals: {post: @post} %>");

app/views/comments/update.js.erb
$("#comment_<%= @comment.id %>").empty().html("<%=j render :partial => 'comments/comment', :locals => {:comment => @comment }%>");

app/views/layouts/_flash_messages.html.erb
<% if flash.alert.present? %>
    <div class="alert alert-danger alert-dismissible" role="alert" style="font-weight: 500">
      <%= flash.alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>
<% if flash.notice.present? %>
    <div class="alert alert-success alert-dismissible" role="alert" style="font-weight: 500">
      <%= flash.notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body style="background-color: #e6e6e6">
<header class="navbar navbar-default" role="navigation" style="background-color: #6747b1; color: white">
  <div class="navbar-inner">
    <div class="container">

      <div class="navbar-brand"><%= link_to "Blog", root_path, style: "color: #c0dbe0" %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <!--user login-->
        <div class="dropdown" style="float: right;margin-top: 15px;">
          <span>Switch link</span>
          <div class="dropdown-content">
            <ul>
              <li><%= link_to 'Post', root_path %></li>
              <li><%= link_to 'Trash', trash_path %></li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </div>
</header>

<!--flash message-->
<div id="main_content">
  <span style="color: red; font-family: Sans-Serif;padding: 2%;margin-left: 166px;"> Note: Authorization and authentication service layer has not been plugged.</span>

  <%= render partial: 'layouts/flash_messages' %>

  <div id="content" class="col-md-9 center-block">
    <%= yield %>
  </div>
</div>
</div>
</body>
</html>

<style>
  .dropdown {
    position: relative;
    display: inline-block;
  }

  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #b2a1da;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    padding: 12px 16px;
    z-index: 1;
  }
  .dropdown-content a {
    text-decoration: none;
  }

  .dropdown:hover .dropdown-content {
    display: block;
  }

</style>

app/views/posts/_form.html.erb
<div class="form-body">
  <%= form_for(@post, remote: true) do |f| %>
      <% if @post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this link from being saved:</h2>

            <ul>
              <% @post.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control", required: true%>
      </div>
      <div class="form-group">
        <%= f.label :describe_post %><br>
        <%= f.text_area :body, class: "form-control", required: true %>
      </div>
      <br>
      <div class="form-group">
        <%= f.submit "#{@post.new_record? ? 'Submit' : 'Update'}", class: "btn btn-lg btn-primary" %>
      </div>

  <% end %>
</div>

app/views/posts/_post_comment_count.html.erb
<h4><%= post.comments.not_soft_destroyed.count %> Comments</h4>

app/views/posts/_posts_box.html.erb
  <div class="link row clearfix" style="background-color: #f5f5f5;">
    <h3 style="margin: 0px;">
      <div class="title-link"> <%= post.title %></div><br>
    </h3>
    <div class="btn-group">
      <%= link_to edit_post_path(id: post.id), :remote => true, :class => "btn btn-primary" do %>
          <i class="fa fa-plus" aria-hidden="true"></i> Edit
      <% end %>
      <%= link_to 'Hard Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_post btn btn-danger' %>
      <%= link_to 'View',post_path(post), :remote => true, :class => "btn btn-success" %>
      <%= link_to 'Soft Delete',soft_destroy_path(id: post.id), :remote => true, method: :post, :class => "btn btn-default" %>
    </div>
  </div>
<hr>

app/views/posts/create.js.erb
$('#render_form_data').empty().html("<%=j render :template => 'posts/show.html.erb' %>");
$('#render_form_data').append("<p style='cole: green'> Succesfully created post </p>");
$('#post_container').append("<div id='link_<%= @post.id%>'> <%=j render :partial => 'posts/posts_box', :locals => {:post => @post}%> </div>");

app/views/posts/destroy.js.erb
$("#link_<%= @post_id%>").remove();
$("#form_data_div").hide()

app/views/posts/edit.js.erb
$('#render_form_data').empty().html("<%=j render :partial => 'posts/form' %>");
$("#form_data_div").show()

app/views/posts/fail_create.js.erb
$('#render_form_data').append("<p style='color: red'> could not create post due to <%= @error %></p>");

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="add-btn">
        <%= link_to new_post_path, :remote => true, :class => "btn btn-primary" do %>
            <i class="fa fa-plus" aria-hidden="true"></i>  Add Post
        <% end %>
      </div>

      <div id="post_container">
        <% @posts.each do |post| %>
            <div id="link_<%= post.id%>" >
              <%= render :partial => 'posts/posts_box', :locals => {:post => post}%>
            </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <div id="form_data_div" style="display:none; width: auto;">
        <button type="button" class="close">&times;</button>
        <h4 class="modal-title"> Post </h4>
        <div class="mem-form" id="render_form_data">
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  #form_data_div {
    width: auto;
    display: block;
    background: #bdb7c3;
    height: auto;
    overflow: auto;
    padding: 2%;
    margin-bottom: 2%;
    margin-top: 6%;
  }
  .add-btn{
    margin-bottom: 4%;
  }
  a:visited {
    color: white;
  }
</style>

<script>
  $('.close').click(function(){
    $('#form_data_div').hide();
  });

</script>

app/views/posts/new.js.erb
$('#render_form_data').empty().html("<%=j render :partial => 'posts/form' %>");
$("#form_data_div").show()

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"><%= @post.title %></h1>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
        | <%= link_to edit_post_path(id: @post.id), :remote => true, :class => "btn btn-primary" do %>
        <i class="fa fa-plus" aria-hidden="true"></i> Edit
    <% end %>
    <%= link_to 'Hard Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_post btn btn-danger' %>
    <%= link_to 'Soft Delete',soft_destroy_path(id: @post.id), :remote => true, method: :post, :class => "btn btn-default" %>

  </p>
  <p class="body"><%= @post.body %></p>


  <div id="comments">
    <div id="comment_count">
      <%= render partial: 'posts/post_comment_count', locals: {post: @post} %>
    </div>
    <% @post.comments.not_soft_destroyed.each do |comment| %>
        <div id="comment_<%= comment.id %>" >
          <%= render partial: 'comments/comment', locals: {comment: comment} %>
        </div>
        <% end %>
    </div>

    <h4>Add a comment:</h4>
  <div class="comment-form">
    <%= render partial: 'comments/form', locals: {post: @post, comment: @post.comments.build } %>
    </div>
  </div>
</div>

app/views/posts/show.js.erb
$('#render_form_data').empty().html("<%=j render :template => 'posts/show.html.erb' %>");
$("#form_data_div").show()

app/views/posts/soft_destroy.js.erb
$("#link_<%= @post_id%>").remove();
$("#form_data_div").hide()

app/views/posts/update.js.erb
$('#render_form_data').empty().html("<%=j render :template => 'posts/show.html.erb' %>");
$('#render_form_data').append("<p style='color: green'> Succesfully Updated post </p>");
$("#link_<%= @post.id%>").empty().html("<%=j render :partial => 'posts/posts_box', :locals => {:post => @post }%>");

app/views/trashes/_soft_deleted_comments.html.erb
<div id="comment_<%= comment.id %>" style="background-color: whitesmoke; padding: 2%;" >
  <div class="comment_content">
    <p class="comment_body"><b><%= comment.user_name %></b></p>
    <p class="comment_body"><%= comment.body %></p>
  </div>
  <%= link_to 'Restore',restore_path(post_id: comment.post, id: comment.id), :remote => true, method: :post %>
  <hr>
</div>

app/views/trashes/_soft_deleted_posts.html.erb
<div id="link_<%= post.id%>" >
      <div class="link row clearfix" style="background-color: white">
        <h2 style="margin: 0px;">
          <div class="title-link"> <%= post.title %></div><br>
        </h2>
        <div class="btn-group">
          <%= link_to 'Restore',restore_path(post_id: post.id), :remote => true, method: :post , class: "btn btn-primary"%>
        </div>
      </div>
      <hr>
  </div>

app/views/trashes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <h1> Deleted Posts </h1>
      <% @posts.each do |post| %>
          <%= render partial: 'soft_deleted_posts', :locals => {:post => post}%>
      <% end %>
    </div>
    <div class="col-md-4">
        <h1> Deleted Comments </h1>
      <% @map_comments_according_to_post.each do |key,value| %>
          <% value.each do |comment| %>
              <%= render partial: 'soft_deleted_comments', locals: {comment: comment} %>
          <% end %>
      <% end %>
    </div>
  </div>
  </div>


  <style>
    hr {
      border: 0;
      border-top: 2px solid #eee;
      margin: 20px 0;
    }
  </style>


<% if false%>



<% end %>

app/views/trashes/restore.js.erb
<% if params[:post_id].present? && params[:id].present? %>
$("#comment_<%= @comment.id %>").remove();
<% elsif params[:post_id].present? %>
$("#link_<%= @post.id%>").remove();
<% end %>